version: '3.7'
services:
  rs2:
    build:
      dockerfile: ./docker/Dockerfile
      context: .
    environment:
      S3_HOST: minio
      S3_BUCKET: imgbucket
      S3_ACCESS_KEY: minio
      S3_SECRET_KEY: minio123
  minio:
    image: minio/minio:RELEASE.2021-04-22T15-44-28Z
    volumes:
      - ./data:/data
    ports:
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
